--===============================
--USERS
CREATE TABLE users (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
role VARCHAR(20) NOT NULL,      --roles: ADMIN, EMPLOYEE, CUSTOMER
email VARCHAR(255) UNIQUE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
password_hash VARCHAR(255) NOT NULL,
telefone VARCHAR(20) NOT NULL,
cpf CHAR(11) UNIQUE NOT NULL
);


